import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ksbackyard.AssertTest
import com.kazurayam.ksbackyard.QuietBrowserTest
import com.kazurayam.ksbackyard.ScreenshotDriverCensoringTest
import com.kazurayam.ksbackyard.ScreenshotDriverOptionsTest
import com.kazurayam.ksbackyard.ScreenshotDriverResizingTest
import com.kazurayam.ksbackyard.ScreenshotDriverTest
import com.kazurayam.ksbackyard.URLParserTest


runWithJUnitRunner(AssertTest.class)
runWithJUnitRunner(QuietBrowserTest.class)
runWithJUnitRunner(ScreenshotDriverCensoringTest.class)
runWithJUnitRunner(ScreenshotDriverOptionsTest.class)
runWithJUnitRunner(ScreenshotDriverResizingTest.class)
runWithJUnitRunner(ScreenshotDriverTest.class)
runWithJUnitRunner(URLParserTest.class)
