import com.kazurayam.imagedifference.ImageDifferenceSerializerTest
import com.kazurayam.imagedifference.ImageDifferenceTest

CustomKeywords.'com.kazurayam.ksbackyard.junit.JUnitCustomKeywords.runWithJUnitRunner'(ImageDifferenceSerializerTest.class)
CustomKeywords.'com.kazurayam.ksbackyard.junit.JUnitCustomKeywords.runWithJUnitRunner'(ImageDifferenceTest.class)
